const fs=require('node:fs');
const html=fs.readFileSync('template.html','utf8'),app=fs.readFileSync('app.js','utf8');
const target='../index.html';
const assetDir=target.startsWith('../')?'../assets':'assets';
const dataUri=(name,mime)=>'data:'+mime+';base64,'+fs.readFileSync(assetDir+'/'+name).toString('base64');
const build=(script,local=false)=>html.replace('__LARA_IMAGE__',()=>local?dataUri('lara-prime-lar.webp','image/webp'):'assets/lara-prime-lar.webp').replace('__LOGO_IMAGE__',()=>local?dataUri('prime-lar-logo.jpg','image/jpeg'):'assets/prime-lar-logo.jpg').replace('__APP_SCRIPT__',()=>script);
fs.writeFileSync(target,build(app));
const prompt=fs.readFileSync('PROMPT_LARA_PRIME_LAR.txt','utf8');
const edge=fs.readFileSync('index.ts','utf8').replace(/^const INSTRUCOES = .*;$/m,()=> 'const INSTRUCOES = '+JSON.stringify(prompt)+';');
fs.writeFileSync('index.ts',edge);
let demoApp=app.replace(/const SESSION_KEY=.*;/,'const SESSION_KEY="lara_prime_review_credentials_v23", HISTORY_KEY="lara_prime_review_tab_v23";');
const start=demoApp.indexOf('async function call('),end=demoApp.indexOf('async function ensureSession',start);
demoApp=demoApp.slice(0,start)+fs.readFileSync('demo.js','utf8')+'\n'+demoApp.slice(end);
let preview=build(demoApp,true);
preview=preview.replace('Atendimento por IA · Teresina e região','Prévia · respostas demonstrativas');
preview=preview.replace('Ao transcrever, o áudio será processado por IA. O texto volta para esta caixa para você revisar e enviar.','Nesta prévia você pode gravar e ouvir localmente. A transcrição real aguarda implantação.');
preview=preview.replace('Suas mensagens são processadas pelo serviço de IA e registradas no ambiente de atendimento para manter o contexto da conversa.','Nesta prévia, as respostas são demonstrativas: mensagens e áudio não são enviados ao servidor.');
preview=preview.replace('A Lara é uma assistente virtual por inteligência artificial.','A Lara será uma assistente virtual por inteligência artificial. Esta é uma prévia para revisar o fluxo.');
preview=preview.replace('ao tocar em “Transcrever”, ele é enviado ao serviço de IA para gerar texto.','a transcrição por IA aguarda implantação e está desativada nesta prévia.');
preview=preview.replace('não apaga os registros já feitos no atendimento.','nesta prévia não há registros enviados ao servidor.');
preview=preview.replace('Mensagens processadas por IA e registradas para este atendimento.','Prévia local para revisão. Respostas demonstrativas, sem conexão com a IA.');
preview=preview.replace('Protocolo da sua conversa','Protocolo demonstrativo');
fs.writeFileSync('LARA_PRIME_LAR_PREVIA.html',preview);
console.log('Interface e prévia compiladas; roteiro sincronizado com a função.');

if(fs.existsSync('widget-preview-template.html'))fs.writeFileSync('LARA_PRIME_LAR_WIDGET_PREVIA.html',fs.readFileSync('widget-preview-template.html','utf8').replace('__PREVIEW_DATA__',()=>JSON.stringify(preview).replace(/</g,'\\u003c')));
